.PHONY: clean All

All:
	@echo "----------Building project:[ Section19_Challenge2 - Debug ]----------"
	@cd "Section19_Challenge2" && "$(MAKE)" -f  "Section19_Challenge2.mk"
clean:
	@echo "----------Cleaning project:[ Section19_Challenge2 - Debug ]----------"
	@cd "Section19_Challenge2" && "$(MAKE)" -f  "Section19_Challenge2.mk" clean
