.PHONY: clean All

All:
	@echo "----------Building project:[ Section19_Challenge1 - Debug ]----------"
	@cd "Section19_Challenge1" && "$(MAKE)" -f  "Section19_Challenge1.mk"
clean:
	@echo "----------Cleaning project:[ Section19_Challenge1 - Debug ]----------"
	@cd "Section19_Challenge1" && "$(MAKE)" -f  "Section19_Challenge1.mk" clean
