.PHONY: clean All

All:
	@echo "----------Building project:[ Section19_Challenge3 - Debug ]----------"
	@cd "Section19_Challenge3" && "$(MAKE)" -f  "Section19_Challenge3.mk"
clean:
	@echo "----------Cleaning project:[ Section19_Challenge3 - Debug ]----------"
	@cd "Section19_Challenge3" && "$(MAKE)" -f  "Section19_Challenge3.mk" clean
