.PHONY: clean All

All:
	@echo "----------Building project:[ First_Class - Debug ]----------"
	@cd "First_Class" && "$(MAKE)" -f  "First_Class.mk"
clean:
	@echo "----------Cleaning project:[ First_Class - Debug ]----------"
	@cd "First_Class" && "$(MAKE)" -f  "First_Class.mk" clean
