.PHONY: clean All

All:
	@echo "----------Building project:[ ImplementingMethods - Debug ]----------"
	@cd "ImplementingMethods" && "$(MAKE)" -f  "ImplementingMethods.mk"
clean:
	@echo "----------Cleaning project:[ ImplementingMethods - Debug ]----------"
	@cd "ImplementingMethods" && "$(MAKE)" -f  "ImplementingMethods.mk" clean
