.PHONY: clean All

All:
	@echo "----------Building project:[ Section6_Challenge - Debug ]----------"
	@cd "Section6_Challenge" && "$(MAKE)" -f  "Section6_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section6_Challenge - Debug ]----------"
	@cd "Section6_Challenge" && "$(MAKE)" -f  "Section6_Challenge.mk" clean
