.PHONY: clean All

All:
	@echo "----------Building project:[ Section7_Challenge - Debug ]----------"
	@cd "Section7_Challenge" && "$(MAKE)" -f  "Section7_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section7_Challenge - Debug ]----------"
	@cd "Section7_Challenge" && "$(MAKE)" -f  "Section7_Challenge.mk" clean
