.PHONY: clean All

All:
	@echo "----------Building project:[ Section20_Challenge1 - Debug ]----------"
	@cd "Section20_Challenge1" && "$(MAKE)" -f  "Section20_Challenge1.mk"
clean:
	@echo "----------Cleaning project:[ Section20_Challenge1 - Debug ]----------"
	@cd "Section20_Challenge1" && "$(MAKE)" -f  "Section20_Challenge1.mk" clean
