.PHONY: clean All

All:
	@echo "----------Building project:[ Section20_Challenge2 - Debug ]----------"
	@cd "Section20_Challenge2" && "$(MAKE)" -f  "Section20_Challenge2.mk"
clean:
	@echo "----------Cleaning project:[ Section20_Challenge2 - Debug ]----------"
	@cd "Section20_Challenge2" && "$(MAKE)" -f  "Section20_Challenge2.mk" clean
