.PHONY: clean All

All:
	@echo "----------Building project:[ Section18_Challenge - Debug ]----------"
	@cd "Section18_Challenge" && "$(MAKE)" -f  "Section18_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section18_Challenge - Debug ]----------"
	@cd "Section18_Challenge" && "$(MAKE)" -f  "Section18_Challenge.mk" clean
