.PHONY: clean All

All:
	@echo "----------Building project:[ Section4_Challenge - Debug ]----------"
	@cd "Section4_Challenge" && "$(MAKE)" -f  "Section4_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section4_Challenge - Debug ]----------"
	@cd "Section4_Challenge" && "$(MAKE)" -f  "Section4_Challenge.mk" clean
