.PHONY: clean All

All:
	@echo "----------Building project:[ Section16_Challenge - Debug ]----------"
	@cd "Section16_Challenge" && "$(MAKE)" -f  "Section16_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section16_Challenge - Debug ]----------"
	@cd "Section16_Challenge" && "$(MAKE)" -f  "Section16_Challenge.mk" clean
