.PHONY: clean All

All:
	@echo "----------Building project:[ Section15_Challenge - Debug ]----------"
	@cd "Section15_Challenge" && "$(MAKE)" -f  "Section15_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section15_Challenge - Debug ]----------"
	@cd "Section15_Challenge" && "$(MAKE)" -f  "Section15_Challenge.mk" clean
