.PHONY: clean All

All:
	@echo "----------Building project:[ Section17_Challenge - Debug ]----------"
	@cd "Section17_Challenge" && "$(MAKE)" -f  "Section17_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section17_Challenge - Debug ]----------"
	@cd "Section17_Challenge" && "$(MAKE)" -f  "Section17_Challenge.mk" clean
