.PHONY: clean All

All:
	@echo "----------Building project:[ Section14_Challenge - Debug ]----------"
	@cd "Section14_Challenge" && "$(MAKE)" -f  "Section14_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section14_Challenge - Debug ]----------"
	@cd "Section14_Challenge" && "$(MAKE)" -f  "Section14_Challenge.mk" clean
