.PHONY: clean All

All:
	@echo "----------Building project:[ Section10_Assignment - Debug ]----------"
	@cd "Section10_Assignment" && "$(MAKE)" -f  "Section10_Assignment.mk"
clean:
	@echo "----------Cleaning project:[ Section10_Assignment - Debug ]----------"
	@cd "Section10_Assignment" && "$(MAKE)" -f  "Section10_Assignment.mk" clean
