.PHONY: clean All

All:
	@echo "----------Building project:[ Section10_Challange - Debug ]----------"
	@cd "Section10_Challange" && "$(MAKE)" -f  "Section10_Challange.mk"
clean:
	@echo "----------Cleaning project:[ Section10_Challange - Debug ]----------"
	@cd "Section10_Challange" && "$(MAKE)" -f  "Section10_Challange.mk" clean
